// <auto-generated />
namespace Rad3012223.ClubData.ClassLibrary.Week5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addingstudentsmembersandclub : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingstudentsmembersandclub));
        
        string IMigrationMetadata.Id
        {
            get { return "202210271850390_adding students, members and club"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
