// <auto-generated />
namespace Rad3012223.ClubData.ClassLibrary.Week5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addingclubadmins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingclubadmins));
        
        string IMigrationMetadata.Id
        {
            get { return "202212141240094_adding-club-admins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
